version: "3"
services:
  django:
    build: ./django
    container_name: django
    command: bash -c "
      python3 manage.py collectstatic --no-input &&
      python3 manage.py makemigrations && 
      python3 manage.py migrate && 
      gunicorn Django.wsgi:application --bind 0.0.0.0:8000 "
    expose:
      - "8000"
    volumes:
      - ./django:/webserver/src

  nginx:
    build: ./config/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./django/static:/webserver/src/static
    depends_on:
      - django
